### ISSUE TITLE
Allow on-the-fly resolution computation for dynamic areas

### ISSUE THREAD

**Issue by mraspaud** [pytroll/pyresample#141]
#### Code Sample, a minimal, complete, and verifiable piece of code

```yaml
europe:
  description: Europe
  projection:
    ellps: WGS84
    lon_0: 0
    proj: stere
    lat_ts: 60
    lat_0: 90
  # shape:
  #   height: 2048
  #   width: 2560
  area_extent:
    lower_left_xy: [-3780000.0, -7644000.0]
    upper_right_xy: [3900000.0, -1500000.0]
    units: m

```
#### Problem description

The current implementation of `DynamicAreas` doesn't allow both size and resolution missing.
However, using the input data for resampling, it is in theory possible to compute how many pixels to resample fall inside the designated area extent, and hence we could compute an approximate size in x and y that would fit the current data.

#### Expected Output

A frozen area with near-optimal resolution for the data at hand.
