### ISSUE TITLE
Duplicate data when resampling to Eckert IV projection and area spans 180th meridian

### ISSUE THREAD

**Issue by pnuu** [pytroll/pyresample#266]
#### Code Sample, a minimal, complete, and verifiable piece of code

```python
from satpy import Scene
import glob

fnames = glob.glob('IMG_DK*')
glbl = Scene(reader='ahi_hrit', filenames=fnames)
glbl.load(['dust'])
lcl = glbl.resample("eckert_iv_global_2km", radius_of_influence=30e3)
lcl.save_datasets(base_dir='/tmp')
```
And the area definition:
```yaml
eckert_iv_global_2km:
  description: Eckert IV global area with 2 km resolution
  projection:
    ESRI:54012
  shape:
    height: 8313
    width: 16921
  area_extent:
    lower_left_xy: [-16921201.240, -8245471.428]
    upper_right_xy: [16916798.760, 8250528.572]
```

#### Problem description

Some of the data are duplicated *outside* the valid area.

#### Expected Output
This image is created with `gdalwarp` from a full disk image in `geos` projection with Satpy.

![gdalwarp_eckert_iv_scaled](https://user-images.githubusercontent.com/3170788/78887493-a0222080-7a68-11ea-8e77-49f88827a6fd.png)

#### Actual Result, Traceback if applicable
This is the (scaled) output from the above code and area definition.

![satpy_eckert_iv_scaled](https://user-images.githubusercontent.com/3170788/78887614-da8bbd80-7a68-11ea-92ae-d79a20735723.png)

Note in particular the (duplicate) cloud formation in top-left and top-right regions.

#### Versions of Python, package at hand and relevant dependencies
Satpy: 0.16.2.dev149+g4313bb4f
Pyresample: 1.15.0+2.g3d6d38d
Pyproj: 2.4.1
Proj: 6.2.1
