### ISSUE TITLE
area not equal after storing and loading

### ISSUE THREAD

**Issue by gerritholl** [pytroll/pyresample#430]
#### Code Sample, a minimal, complete, and verifiable piece of code

```python
from pyproj import CRS
from pyresample import create_area_def
from pyresample.area_config import load_area_from_string
ar = create_area_def("test", CRS.from_authority("IAU_2015", 39916), area_extent=[-10_000_000, -10_000_000, 10_000_000, 10_000_000], resolution=10000)
ar2 = load_area_from_string(ar.dump())
print(ar == ar2)
```
#### Problem description

After storing and loading, the areas should be equal.  Even considering floating point precision.

#### Expected Output

```
True
```

#### Actual Result, Traceback if applicable

```
/data/gholl/mambaforge/envs/py310/lib/python3.10/site-packages/pyproj/crs/crs.py:1256: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  return self._crs.to_proj4(version=version)
False
```

#### Versions of Python, package at hand and relevant dependencies

pyresample v1.23.0.

**Comment by djhoese** [comment]
Can you show what the `.dump()` output is?

**Comment by gerritholl** [comment]
`ar.dump()` and `ar2.dump()` are actually equal:

```
test:
  description: test
  projection:
    proj: eqc
    lat_ts: 0
    lat_0: 0
    lon_0: 180
    x_0: 0
    y_0: 0
    a: 6378136.6
    rf: 298.257006177324
    no_defs: null
    type: crs
  shape:
    height: 2000
    width: 2000
  area_extent:
    lower_left_xy: [-10000000.0, -10000000.0]
    upper_right_xy: [10000000.0, 10000000.0]
    units: m

test:
  description: test
  projection:
    proj: eqc
    lat_ts: 0
    lat_0: 0
    lon_0: 180
    x_0: 0
    y_0: 0
    a: 6378136.6
    rf: 298.257006177324
    no_defs: null
    type: crs
  shape:
    height: 2000
    width: 2000
  area_extent:
    lower_left_xy: [-10000000.0, -10000000.0]
    upper_right_xy: [10000000.0, 10000000.0]
    units: m
```
